version: "3.1"
services:

    redis:
      image: redis:5.0.1-alpine
      container_name: "${PROJECT_NAME}-redis"
      environment:
        - TZ=${TIMEZONE}

    mariadb:
      image: mariadb:10.1
      container_name: "${PROJECT_NAME}-db"
      volumes:
        - ./docker/database:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
        - TZ=${TIMEZONE}
      ports:
        - '3306:3306'

    webserver:
      image: nginx:alpine
      container_name: "${PROJECT_NAME}-nginx"
      working_dir: /application
      volumes:
          - ./project:/application
          - ./docker/nginx/logs:/var/log/nginx/
          - ./docker/nginx/vhosts/docker.conf:/etc/nginx/conf.d/docker.conf
      ports:
          - "80:80"
      links:
          - "php-fpm"
      environment:
          - TZ=${TIMEZONE}

    php-fpm:
      build: docker/php-fpm
      container_name: ${PROJECT_NAME}-php
      volumes:
        - ./project:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      links:
        - "mariadb"
      environment:
        - TZ=${TIMEZONE}

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: ${PROJECT_NAME}-myadmin
      ports:
        - "8080:80"
      links:
        - "mariadb"
      environment:
        - TZ=${TIMEZONE}
        - PMA_ARBITRARY=1
        - PMA_HOST=${PROJECT_NAME}-myadmin
